---
- name: Retirement playbook
  hosts: all
  tasks: 
    - name: Remove file from guest vm
      file:
        path: /tmp/ansible-pre-playbook
        state: absent 
    - name: Touch new file on guest vm
      file:
        path: /tmp/ansible-post-playbook
        state: touch

